# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Majeed Thaika
name: Majeed Thaika
email: majeed.thaika@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blogging my exciting endeavours into the magic that is the digital world.
url: "https://github.com/majeedthaika" # the base hostname & protocol for your site
github_username:  majeedthaika

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
